version: '3.8'

services:
  netbird:
    image: netbirdio/netbird
    container_name: netbird
    hostname: netbird
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    environment:
      - NB_SETUP_KEY=f6d07546-cb0b-4193-960f-0a343a04f56a
    volumes:
      - netbird-client:/etc/netbird
    restart: unless-stopped

volumes:
  netbird-client:
